# NB : remember filter must stay before every other filter, else, we get this strange behaviour, 
# where header shows we are identified, and homepage does not display "add outing" due to cache
rememberFilter:
  class: rememberFilter
  
rendering: ~
web_debug: ~
security:  ~

# generally, you will want to insert your own filters here :
FiltersSwitchFilter:
  class: FiltersSwitchFilter
  
# MyCacheFilter replaces the original filter to enable action caching with user's culture :
cache:
  class: MyCacheFilter
  param:
    condition: %SF_CACHE%

common:    ~    

flash:     ~

# switch between regular and mobile version of the site
MobileFilter:
  class: MobileFilter

# MyExecutionFilter replaces the original filter to enable action caching with user's culture :execution:
execution:
  class: MyExecutionFilter
  param:
    type: execution
