default:
  http_metas:
    content-type: text/html
    X-UA-Compatible: "IE=8,chrome=1" # Set to "IE=edge,chrome=1" once ie9 problems are solved. TODO check if X-Ua-Compatible is ok

  metas:
    title:        meta_title
    robots:       noindex, follow
    description:  meta_description
    keywords:     meta_keywords
    language:     meta_language

  stylesheets:
    - /static/css/main.css: { media: all }
  #  - /static/css/menu.css: { media: all }
  #  - /static/css/handheld.css: { media: handheld, position: last }
  #  - /static/css/print.css: { media: print, position: last }
  # javascripts should not be specified here if not application-wide

  has_layout:     on
  layout:         layout
