default:
  metas:
    title:        meta_title
    robots:       noindex, follow
    description:  meta_description
    keywords:     meta_keywords

  stylesheets:
    - /static/css/main.css: { media: all }
    - /static/css/img.css: { media: all }
  # javascripts should not be specified here if not application-wide

  has_layout:     on
  layout:         layout
