default:
  metas:
    title:        meta_title
    robots:       noindex, follow
    description:  meta_description
    keywords:     meta_keywords

  # stylesheets:
  # javascripts should not be specified here if not application-wide
  javascripts: [ /static/js/queue.js, /static/js/misc.js ]

  has_layout:     on
  layout:         layout
