all:
  public_transportation_ratings:
    list:
      0:
      1: good service
      2: poor service
      3: no service

  snow_clearance_ratings:
    list:
      0:
      1: often cleared
      2: sometimes cleared
      3: naturally cleared
