all:
  snow_clearance_ratings:
    list:
      0:
      1: often cleared
      2: sometimes cleared
      3: naturally cleared
  public_transportation_types:
    list:
      0:
      1: train
      2: bus
      3: on_demand_service

  sort:
    criteria:
      'pnam': 'name'
      'palt': 'elevation'
      'tp': 'public_transportation_rating'
      'anam': 'region_name'
      'geom': 'geom_wkt'
