all:
  snow_clearance_ratings:
    list:
      0:
      1: often cleared
      2: sometimes cleared
      3: naturally cleared
      4: non applicable

  sort:
    criteria:
      'pnam': 'name'
      'palt': 'elevation'
      'tp': 'public_transportation_rating'
      'tpty': 'public_transportation_types'
      'anam': 'region_name'
      'geom': 'geom_wkt'
