all:
  hut_statuses:
    list:
      0:
      2: opened staffed
      4: opened unstaffed
      6: closed hut

  frequentation_statuses:
    list:
      0:
      1: desert
      2: some people
      4: quite crowded
      3: lots of people

  conditions_statuses:
    list:
      0:
      1: excellent conditions
      2: good conditions
      3: mean conditions
      4: poor conditions
      5: awful conditions

  access_statuses:
    list:
      0:
      2: cleared road
      4: snowy road
      6: closed road
  
  lift_statuses:
    list:
      0:
      2: opened lift
      4: closed lift

  glacier_statuses:
    list:
      0:
      2: easy crossing
      4: possible crossing
      6: difficult crossing
      8: impossible crossing

  track_statuses:
    list:
      0:
      1: good track
      2: mean track
      3: poor track

  conditions_levels:
    fields:
      1: level_place
      2: level_snow_height_soft
      3: level_snow_height_total
      4: level_comment

  ages:
    values:
      0:
      '1D': '1'
      '2D': 2
      '3D': 3
      '4D': 4
      '5D': 5
      '6D': 6
      '1W': '1'
      '10D': 10
      '2W': 2
      '3W': 3
      '1M': '1'
      '2M': 2
      '3M': 3
      '4M': 4
      '6M': 6
      '1Y': '1'
      '2Y': 2
      '3Y': 3
      '5Y': 5
      '10Y': 10

  ages:
    units:
      0:
      '1D': day
      '2D': days
      '3D': days
      '4D': days
      '5D': days
      '6D': days
      '1W': week
      '10D': days
      '2W': weeks
      '3W': weeks
      '1M': month
      '2M': months
      '3M': months
      '4M': months
      '6M': months
      '1Y': year
      '2Y': years
      '3Y': years
      '5Y': years
      '10Y': years

  sort:
    criteria:
      'onam': name
      'act':  activities
      'date': date
      'alt':  max_elevation
      'hdif': height_diff_up
      'cond': conditions_status
      'anam': region_name
      'geom': geom_wkt

  recent_conditions_limit: 3W

  # duplicated from routes config, so that it can be used
  # as a search criteria for outings
  sub_activities:
    list:
      0:
      1: ski
      2: snowboard
      3: snowshoes
      4: beginner_proof
