all:
  editors:
    list:
      1: IGN
      2: Swisstopo
  scales:
    list:
      1: 1/25000
      2: 1/50000
      3: 1/100000

  sort:
    criteria:
      'mnam': name
      'code': code
      'scal': scale
      'edit': editor
