all:
  shelter_types:
    list:
      0:
      1: building
      5: gite
      2: shelter
      3: camping area
      4: basecamp

  sort:
    criteria:
      'hnam': name
      'halt': elevation
      'styp': shelter_type
      'hscap': staffed_capacity
      'hucap': unstaffed_capacity
      'act':  activities
      'anam': region_name
      'lat': 'location S >> N'
      'lon': 'location W >> E'
