querySuccess:
  javascripts: [ /static/js/openlayers_sfl/OpenLayers, /static/js/cartoweb/lib/CartoWeb, /static/js/cartoweb/lib/Search, /static/js/cartoweb/lib/SearchForm, /static/js/search, /static/js/fold ]
  
#historySuccess:
#  javascripts:    [ /static/js/diff ]
# does not work for historySuccess for an unknown reason

editSuccess:
  javascripts:    [ /static/js/bbcode, /static/js/routes ]

viewSuccess:
  javascripts:    [ /static/js/fold ] 

# warning (FIXME ?) : if we specify : {position: last} they do not appear at all.

getratingsSuccess:
  has_layout: no
