all:
  categories:
    list:
      1: landscapes pic
      6: detail pic
      4: topo pic
      3: action pic
      7: track pic
      8: rise pic
      9: descent pic
      2: people pic
      10: fauna pic
      11: flora pic
      12: geology pic
      13: hut pic
      14: equipment pic
      5: misc pic

  sort:
    criteria:
      'inam': name
      'anam': region_name
      'auth': author
      'act':  activities
      'cat':  categories
      'date': date

  license:
    list:
      1: personal content
      2: collaborative content
