querySuccess:
  javascripts: [ /static/js/openlayers_sfl/OpenLayers, /static/js/cartoweb/lib/CartoWeb, /static/js/cartoweb/lib/Search, /static/js/cartoweb/lib/SearchForm, /static/js/search, /static/js/fold ]
  
#historySuccess:
#  javascripts:    [ %APP_STATIC_URL%/static/js/diff.js?<?php echo sfSVN::getHeadRevision('diff.js') ?> ]
# does not work for historySuccess for an unknown reason

editSuccess:
  javascripts:    [ %APP_STATIC_URL%/static/js/bbcode.js?<?php echo sfSVN::getHeadRevision('bbcode.js') ?> ]

viewSuccess:
  javascripts:    [ %APP_STATIC_URL%/static/js/fold.js?<?php echo sfSVN::getHeadRevision('fold.js') ?> ] 
  
# warning (FIXME ?) : if we specify : {position: last} they do not appear at all.

popupSuccess:
  layout: popup