all:
  ml_owner: listowner@camptocamp.org
  mailinglists:
    values: [ 'avalanche', 'lawinen', 'valanghe', 'avalanche.en', 'meteofrance-38', 'meteofrance-74', 'meteofrance-73', 'meteofrance-04', 'meteofrance-05', 'meteofrance-06', 'meteofrance-31', 'meteofrance-64', 'meteofrance-65', 'meteofrance-66', 'meteofrance-09', 'meteofrance-andorre', 'meteofrance-2a', 'meteofrance-2b' ]

  sort:
    criteria:
      'unam': name
      'anam': region_name
      'act':  activities
      'cat':  category

  category:
    list:
      0:
      1: amateur
      2: pro
      3: club
      4: institution

  profile_cookies:
    list: [ 'punbb_dyncat', 'filter_switch', 'filtered_places_type', 'filtered_places', 'filtered_activities', 'filtered_languages', 'nav_about_home_status', 'nav_prepare_home_status', 'nav_toolbox_home_status', 'nav_figures_home_status', 'last_images_home_status', 'last_outings_home_status', 'on_the_web_home_status', 'last_articles_home_status', 'last_mountain_news_home_status', 'last_msgs_home_status', 'last_docs_home_status' ]
