messageResetPasswordSuccess:
  has_layout: no
  
messageSignupPasswordSuccess:
  has_layout: no
  
editPrivateDataSuccess:
  javascripts: [ %APP_STATIC_URL%/static/js/interface_tools.js ]

editSuccess:
  javascripts:    [ %APP_STATIC_URL%/static/js/bbcode.js ]
  
viewSuccess:
  javascripts:    [ %APP_STATIC_URL%/static/js/fold.js ] 
  metas:
    robots:       noindex, follow
