messageResetPasswordSuccess:
  has_layout: no
  
messageSignupPasswordSuccess:
  has_layout: no
  
editSuccess:
  javascripts:    [ %APP_STATIC_URL%/static/js/bbcode.js ]
  
viewSuccess:
  javascripts:    [ %APP_STATIC_URL%/static/js/fold.js ] 
  metas:
    robots:       noindex, follow

popupSuccess:
  layout: popup
