all:
  summit_types:
    list:
      1: culmen
      2: pass
      3: lake
      4: valley
      5: raid

  sort:
    criteria:
      'snam': 'name'
      'salt': 'elevation'
      'styp': 'summit_type'
      'anam': 'region_name'
      'geom': 'geom_wkt'
