#querySuccess:
#  javascripts: [ /static/js/openlayers_sfl/OpenLayers, /static/js/cartoweb/lib/CartoWeb, /static/js/cartoweb/lib/Search, /static/js/cartoweb/lib/SearchForm, /static/js/search, /static/js/fold ]
# does not work for unknown reason (javascripts added in querySuccess.php)
  
#historySuccess:
#  javascripts:    [ /static/js/diff ]
# does not work for unknown reason (javascripts added in historySuccess.php)

editSuccess:
  javascripts:    [ /static/js/bbcode ]

viewSuccess:
  javascripts:    [ /static/js/fold ] 
  
# warning (FIXME ?) : if we specify : {position: last} they do not appear at all.

geoportailSuccess:
  layout: geoportail
